### ISSUE TITLE
Alternatives to Travis

### ISSUE THREAD

**Issue by PeterKrcmar0** [brunnerant/sdp-project#110]
Hi, as mentioned during the meeting if you're having issues with travis you can try looking into alternative CI tools as they are faster and might give you similar results to what you obtain locally.

**CirrusCI**:
- [this team](https://github.com/Ph0tonic/SDP_Projet/wiki/CirrusCi) wrote a small setup tutorial, but they are using Kotlin
- [this team](https://github.com/CoronaTeam/CoronaGame) and [this team](https://github.com/ayman-mezghani/MusiConnect) are using cirrus with Java

**Github actions**:
- have a look at [this team](https://github.com/SachaKor/SDP-PolyCrowd)'s setup and/or search a bit online

Good luck !!! 🤞

**Comment by PeterKrcmar0** [comment]
@cjordan7 @brunnerant @nbaehler @alexisc99 @nathan96g @Anthony-Iozzia

**Comment by brunnerant** [comment]
Thank you for your help, we appreciate it !
