### ISSUE TITLE
Implement the backend interface using Firebase

### ISSUE THREAD

**Issue by brunnerant** [brunnerant/sdp-project#6]
First, we should explore how firebase roughly works, and how we could integrate it in the app.
The first version of the backend should support simple challenge and response protocol for the login.
It means that #3 and #5 should already be done for this issue to be done.

**Comment by cjordan7** [comment]
It took a while to learn about firebase and how to do simple things (creating user, connecting) in it.

**Comment by cjordan7** [comment]
It took a while to implement and connect everything for the project to work with Firebase.

**Comment by cjordan7** [comment]
It took a while as well to implement and correct everything on the code and then push it to the main repo with the help of some other member of the team (Brunner, Iozzia).
